FROM public.ecr.aws/debian/debian:stable-slim@sha256:b44c88c7a0d6e09b8e0699794338fc414da364e1a6eba03fc945f753eb346860

RUN apt update && apt install -y \
      busybox bash \
      iptables ipset dnsmasq dnsutils
