FROM public.ecr.aws/debian/debian:stable-slim@sha256:6f215363c2547a2d34585f3cfa806048b0a766d1dcc9195f06125740f2c60bd1

RUN apt update && apt install -y \
      busybox bash \
      iptables ipset dnsmasq dnsutils
